### PR TITLE
Build Matrix & Build Artifacts

### PR DESCRIPTION
**Pull request by Baggz**
Fixes https://github.com/apiaryio/attributes-kit/issues/173.

## Build Matrix

* Node.js 0.10.40
* Node.js 0.12.7
* Node.js 4.2.2
* Node.js 5.0.0

## Build Artifacts

image

### CODE REVIEW

**Comment by XVincentX** [comment]
Could you update `.npmignore` to ignore those new files? They are not needed in the package.

**Comment by Baggz** [comment]
@XVincentX 

> Could you update `.npmignore` to ignore those new files? They are not needed in the package.

Good point! Done.

**Comment by XVincentX** [comment]
Please test also the thing using `npm pack` and exploring the produced file.

**Comment by Baggz** [comment]
@XVincentX 

Done and verified.

**Comment by XVincentX** [comment]
Ok!

**Pull request merged**
