### PR TITLE
Enable client side parsing with drafter.js

### PR DESCRIPTION
**Pull request by XVincentX**
This PR is a starting point to have a full client side parsing using `drafter.js`

1. `drafter.js` is super slow compared to its C++ counter part. The experience is not the best one. This should be moved to a webworker or the UI will hang (totally)
2. We can't use its npm package given that emscripten has a limitation which I'm actively tracking: https://github.com/kripken/emscripten/issues/2415#issuecomment-158005938

### CODE REVIEW

**Comment by XVincentX** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;eo6bwbJt&#x2F;1226-adopt-js-drafter-in-browser"> Adopt JS Drafter in browser</a>

**Comment by XVincentX** [comment]
Found interesting alternative: https://github.com/webpack/imports-loader

**Comment by XVincentX** [comment]
No, that is not an alternative.

**Comment by XVincentX** [comment]
That PR has been merged: https://github.com/kripken/emscripten/pull/3928

**Comment by Baggz** [comment]
As it's currently not a priority let me close the PR; we might reopen the pull request later on.

**Pull request closed without merging**
